// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY5bumNM74JV3jejDf8zFlKC0ujLf-QJA',
    appId: '1:383480432655:web:d0a30733428353d016fb7a',
    messagingSenderId: '383480432655',
    projectId: 'uas-2020130015',
    authDomain: 'uas-2020130015.firebaseapp.com',
    storageBucket: 'uas-2020130015.appspot.com',
    measurementId: 'G-B86CVY4BCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdXskB-lI2hsxp5Sk4lItIiXteud3ekdk',
    appId: '1:383480432655:android:248e97b07fe7d64c16fb7a',
    messagingSenderId: '383480432655',
    projectId: 'uas-2020130015',
    storageBucket: 'uas-2020130015.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJt--05an9HU0MWH3bbhkqPSK6wXB0HbM',
    appId: '1:383480432655:ios:5e8e336ce272914016fb7a',
    messagingSenderId: '383480432655',
    projectId: 'uas-2020130015',
    storageBucket: 'uas-2020130015.appspot.com',
    iosClientId: '383480432655-sgqd981enrga5dp8hugcbhineqt4fij1.apps.googleusercontent.com',
    iosBundleId: 'com.example.uas2020130015',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJt--05an9HU0MWH3bbhkqPSK6wXB0HbM',
    appId: '1:383480432655:ios:5e8e336ce272914016fb7a',
    messagingSenderId: '383480432655',
    projectId: 'uas-2020130015',
    storageBucket: 'uas-2020130015.appspot.com',
    iosClientId: '383480432655-sgqd981enrga5dp8hugcbhineqt4fij1.apps.googleusercontent.com',
    iosBundleId: 'com.example.uas2020130015',
  );
}
